language: java

cache:
  directories:
    - $HOME/.bin
    - $HOME/.m2

env:
  global:
    - BOOT_EMIT_TARGET=no
    - BOOT_VERSION=2.5.5

jdk:
  - oraclejdk8
  - oraclejdk7

install: ./scripts/install-deps.sh
script:  ./scripts/ci-travis.sh
